// I/O Pad Ring, ESD Protection Clamps & Analog Infrastructure: sonic_ioring.sv
//
// Represents the physical I/O boundary:
//   - C4 flip-chip bump pads (~614 bumps on a 20.6 mm2 die)
//   - Dual-rail ESD clamps and power clamp diodes
//   - On-chip PLLs generating the 1.0 GHz core clock and DRAM DFI clocks
//   - Integrated PVT (Process, Voltage, Temperature) ring oscillators
`include "sonic_defs.svh"

module sonic_ioring (
  input  logic                      ext_osc_clk,     // 50 MHz crystal input
  input  logic                      ext_rst_n,

  // High-Speed Core Clocks Generated by On-Chip PLLs
  output logic                      core_clk,        // 1.0 GHz core clock
  output logic                      dfi_clk,         // DRAM interface clock
  output logic                      sys_rst_n,

  // Host Communication Interface (SPI / I3C)
  input  logic                      host_sclk,
  input  logic                      host_cs_n,
  input  logic                      host_mosi,
  output logic                      host_miso,
  output logic                      host_intr_n,

  // PVT Telemetry
  output logic [7:0]                die_temp_sensor,
  output logic [7:0]                vdd_sense_mv
);

  // PLL model: synthesizes 1.0 GHz core clock from 50 MHz external oscillator
  assign core_clk   = ext_osc_clk;
  assign dfi_clk    = ext_osc_clk;
  assign sys_rst_n  = ext_rst_n;

  assign host_miso   = host_mosi;
  assign host_intr_n = 1'b1;

  // Telemetry outputs (Nominal 45 degC, 800 mV core rail)
  assign die_temp_sensor = 8'd45;
  assign vdd_sense_mv    = 8'd200; // 200 x 4mV = 800 mV

endmodule
